### PR TITLE
Clone snapshots and flatten rbd images before deletion

### LINKED ISSUE #809: Unable to delete `VolumeSnapshot` and source `Volume` used by restored `Volume`
**Describe the bug**
Unable to delete `VolumeSnapshot` if used as a `dataSource` to restore `Volume`. Also source `Volume` cannot be deleted if it has `VolumeSnapshot`s. To delete `Volume` user needs to delete all `VolumeSnapshot`s first and then `Volume` can be deleted.

**To Reproduce**
1. Create `Volume`
2. Create `VolumeSnapshot`
3. Restore `Volume` using `VolumeSnapshot` as `dataSource`
4. Delete `VolumeSnapshot`
5. Delete source `Volume` from step 1

**Expected behavior**
A `VolumeSnapshot` and source `Volume` should be deleted successfully

**Additional context**
`Ceph` implementation does not allow to delete `Volume` if it has `VolumeSnapshot`s.

### PR DESCRIPTION
**Pull request by kasabe28**
# Proposed Changes

- Flatten cloned images of snapshot during snapshot deletion
- Clone snapshots into images and flatten snapshot children if it has before source volume deletion
- Delete volume os-image only if it is not referenced by any other volumes
- Improve error handling in `CreateVolume()`
- Introduce helper functions - `openImage()`, `closeImage()`, `flattenImage()`, `createSnapshot()`, `removeSnapshot()`, `flattenChildImages(), isSnapshotExist()` and use it wherever it can be.

Fixes #809 

## Summary by CodeRabbit

* **Bug Fixes**
  * Deletion flows now clone snapshot sources, flatten child images, and handle finalizers to avoid orphaned data and improve error handling.

* **New Features**
  * Snapshot-based cloning creates managed images that preserve metadata and labels; cloning steps are more traceable via enhanced logs.

* **Improvements**
  * Volume/image creation derives size and optional encryption from snapshot or image sources with safer nil-handling and clearer logging.

* **Chores**
  * Image encryption spec in the public API is now nullable (optional).

* **Tests**
  * Integration tests updated to expect nil encryption for unencrypted volumes and enable more verbose test logging.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Review by gonzolino — COMMENTED** [review]
Review not 100% done yet, but here are some remarks I found so far.

File: internal/controllers/image_controller.go [hunk 1]
```diff
@@ -228,49 +228,191 @@ func (r *ImageReconciler) deleteImage(ctx context.Context, log logr.Logger, ioCt
...
+
+		log.V(2).Info("Create snapshot clone", "snapshotId", snapName)
+		if err := r.cloneImageFromSnapshot(ctx, log, ioCtx, snapName, image); err != nil {
+			return fmt.Errorf("failed to create snapshot clone: %w", err)
+		}
+		log.V(2).Info("Created snapshot clone", "snapshotId", snapName)
+
+		if err := r.deleteImageSnapshot(ctx, log, ioCtx, snapName, snap); err != nil {
+			return fmt.Errorf("failed to delete image snapshot: %w", err)
+		}
```
Comment (gonzolino) [inline internal/controllers/image_controller.go]: In this section, any existing snapshots will be cloned, the cloned images will be flattened and then the snapshots deleted. Before (on line 278), there is a call to `flattenChildImagesIfAny`, which flattens all child images.

I think the flow would be clearer if all snapshots would be cloned, then all child images would be flattened, and only then snapshots would be deleted.

File: internal/controllers/image_controller.go [hunk 2]
```diff
@@ -228,49 +228,191 @@ func (r *ImageReconciler) deleteImage(ctx context.Context, log logr.Logger, ioCt
...
+	}
+	return nil
+}
+
+func (r *ImageReconciler) deleteImageSnapshot(ctx context.Context, log logr.Logger, ioCtx *rados.IOContext, snapName string, snap *librbd.Snapshot) error {
+	// delete the cloned image if next steps fails
+	deleteClone := true
+	defer func() {
+		if deleteClone {
+			if err := r.images.Delete(ctx, snapName); err != nil {
```
Comment (gonzolino) [inline internal/controllers/image_controller.go]: I don't think it's a good idea to have cleanup code here in this function for an image that gets created in a different function. If we ever refactor the code it might happen that we change the order we call functions and it might mess with this cleanup code.

Also, instead of deleting the cloned image in case of a failure, maybe we can keep track of the cloned image and reuse it when we retry the deletion.

File: internal/controllers/snapshot_controller.go [hunk 3]
```diff
@@ -218,18 +185,38 @@ func (r *SnapshotReconciler) deleteSnapshot(ctx context.Context, log logr.Logger
 	}
 	defer closeImage(log, img)
 
-	if err = r.removeSnapshot(log, snapshotID, img); err != nil {
+	if err := flattenChildImagesIfAny(log, ioCtx, img); err != nil {
```
[the remark this answers is not in the document]
Comment (kasabe28) [reply internal/controllers/snapshot_controller.go]: Fixed it by opening rbd image along with snapshot name, so that it will list children originated only from that snapshot.

File: internal/controllers/image_controller.go (hunk 1 above)
Comment (kasabe28) [reply internal/controllers/image_controller.go]: Flow is now changed as mentioned above.

File: internal/controllers/common.go [hunk 4]
```diff
@@ -41,7 +43,109 @@ func getSnapshotSourceDetails(snapshot *providerapi.Snapshot) (parentName string
...
+	if closeErr := img.Close(); closeErr != nil && errors.Is(closeErr, librbd.ErrImageNotOpen) {
 		log.Error(closeErr, "failed to close image")
 	}
 }
+
+func openImage(ioCtx *rados.IOContext, imageName string) (*librbd.Image, error) {
+	img, err := librbd.OpenImage(ioCtx, imageName, librbd.NoSnapshot)
+	if err != nil {
+		if !errors.Is(err, librbd.ErrNotFound) {
+			return nil, fmt.Errorf("failed to open cloned image: %w", err)
```
Comment (gonzolino) [inline internal/controllers/common.go]:
```suggestion
			return nil, fmt.Errorf("failed to open image: %w", err)
```

**Comment by lukasfrank** [comment]
@coderabbitai review

File: internal/controllers/common.go [hunk 5]
```diff
@@ -41,7 +43,95 @@ func getSnapshotSourceDetails(snapshot *providerapi.Snapshot) (parentName string
...
+
+func flattenImage(log logr.Logger, ioCtx *rados.IOContext, imageName string) error {
+	log.V(2).Info("Flatten cloned image", "ImageID", imageName)
+	img, err := openImage(ioCtx, imageName)
+	if err != nil {
+		return err
+	}
+	defer closeImage(log, img)
+
+	if err := img.Flatten(); err != nil {
```
[the remark this answers is not in the document]
Comment (gonzolino) [reply internal/controllers/common.go]: The team decided to keep the `Flatten` operation here for now. At a later point in time we will restructure the code and move the operation out of the controller together with the image population.

File: internal/volumeserver/volume_create.go [hunk 6]
```diff
@@ -24,66 +24,75 @@ func (s *Server) createImageFromVolume(ctx context.Context, log logr.Logger, vol
...
+				return nil, fmt.Errorf("failed to get snapshot source volume from store: %w", err)
 			}
 
-			encryptedPassphrase, err = s.keyEncryption.Encrypt(passphrase)
-			if err != nil {
-				return nil, fmt.Errorf("failed to encrypt passphrase: %w", err)
+			log.V(2).Info("Getting image size and encryption from snapshot source volume", "snapshotSourceVolumeID", snapshotSourceVolume.ID)
+			imageSize = snapshotSourceVolume.Spec.Size
+			if snapshotSourceVolume.Spec.Encryption != nil {
+				encryptionSpec = snapshotSourceVolume.Spec.Encryption
```
[the remark this answers is not in the document]
Comment (gonzolino) [reply internal/volumeserver/volume_create.go]: Tested, the encryption spec must be overwritten.

**Review by gonzolino — APPROVED** [review]
